# Generated by Django 2.0.4 on 2018-06-25 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='display_name',
            field=models.CharField(default='Temporalite User', max_length=128),
            preserve_default=False,
        ),
    ]
