# Generated by Django 2.0.4 on 2018-04-26 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_task_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='workspace',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tasks.Workspace'),
        ),
    ]
