# Generated by Django 2.0.4 on 2018-05-27 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='default_workspace',
        ),
        migrations.RemoveField(
            model_name='account',
            name='user',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
