# Generated by Django 2.0.4 on 2018-05-29 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_auto_20180527_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default=None, max_length=7),
            preserve_default=False,
        ),
    ]
