# Generated by Django 2.0.4 on 2018-06-24 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_auto_20180621_2133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('workspace', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tasks.Workspace')),
            ],
        ),
    ]
