# Generated by Django 2.0.4 on 2018-07-13 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_auto_20180712_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='billable',
            field=models.BooleanField(default=True),
        ),
    ]
