export default {
    USER_LOADING: 'USER_LOADING',
    USER_LOADED: 'USER_LOADED',
    LOGIN: 'LOGIN',
    AUTHENTICATION_ERROR: 'AUTHENTICATION_ERROR',
    LOGIN_FAILED: 'LOGIN_FAILED',
    LOGOUT: 'LOGOUT',
    WORKSPACE_LOADING: 'WORKSPACE_LOADING',
    WORKSPACE_LOADED: 'WORKSPACE_LOADED',
    FETCH_FAILED: 'FETCH_FAILED',
    SPRINT_LOADING: 'SPRINTS_LOADING',
    SPRINT_LOADED: 'SPRINTS_LOADED'
}