export default {
    USER_LOADING: 'USER_LOADING',
    USER_LOADED: 'USER_LOADED',
    LOGIN: 'LOGIN',
    AUTHENTICATION_ERROR: 'AUTHENTICATION_ERROR',
    LOGIN_FAILED: 'LOGIN_FAILED',
    LOGOUT: 'LOGOUT'
}